default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin

stages:
  - build
  - test
  - release
  - deploy

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

  CONTAINER_FRONTEND_IMAGE: onset-frontend
  CONTAINER_BACKEND_IMAGE: onset-backend

build-frontend:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_FRONTEND_IMAGE:$CI_COMMIT_REF_SLUG ./frontend
    - docker tag $CONTAINER_FRONTEND_IMAGE:$CI_COMMIT_REF_SLUG $CONTAINER_FRONTEND_IMAGE:latest
    - docker push $CONTAINER_FRONTEND_IMAGE:latest
    - docker push $CONTAINER_FRONTEND_IMAGE:$CI_COMMIT_REF_SLUG

build-backend:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_BACKEND_IMAGE:$CI_COMMIT_REF_SLUG ./backend
    - docker tag $CONTAINER_BACKEND_IMAGE:$CI_COMMIT_REF_SLUG $CONTAINER_BACKEND_IMAGE:latest
    - docker push $CONTAINER_BACKEND_IMAGE:latest
    - docker push $CONTAINER_BACKEND_IMAGE:$CI_COMMIT_REF_SLUG

# deploy:
#   stage: deploy
#   script:
#     - ./deploy.sh
#   rules:
#     - if: $CI_COMMIT_BRANCH == "main"
#   environment: production