default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin

stages:
  - build
  - test
  - release
  - deploy

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  CONTAINER_FRONTEND_IMAGE: onset-frontend
  CONTAINER_BACKEND_IMAGE: onset-backend
  CONTAINER_FRONTEND_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

build-frontend:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_FRONTEND_IMAGE ./frontend
    - docker tag $CONTAINER_FRONTEND_IMAGE $CONTAINER_FRONTEND_IMAGE:$CI_COMMIT_REF_SLUG
    - docker push $CONTAINER_FRONTEND_IMAGE

build-backend:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_BACKEND_IMAGE ./backend
    - docker tag $CONTAINER_BACKEND_IMAGE $CONTAINER_BACKEND_IMAGE:$CI_COMMIT_REF_SLUG
    - docker push $CONTAINER_BACKEND_IMAGE

# deploy:
#   stage: deploy
#   script:
#     - ./deploy.sh
#   rules:
#     - if: $CI_COMMIT_BRANCH == "main"
#   environment: production